#!/bin/bash

echo "📋 После получения нового токена выполните:"
echo ""
echo "1️⃣  Обновите .env.local на сервере:"
echo "   ssh root@82.97.253.12"
echo "   nano /var/www/alu.stella-spb.ru/.env.local"
echo "   # Замените TELEGRAM_BOT_TOKEN=старый на TELEGRAM_BOT_TOKEN=новый"
echo ""
echo "2️⃣  Перезапустите приложение:"
echo "   pm2 restart crm"
echo ""
echo "3️⃣  Проверьте, что новый токен работает:"
echo "   curl 'https://api.telegram.org/bot<НОВЫЙ_ТОКЕН>/getMe'"
echo ""
echo "4️⃣  Проверьте, что старый токен НЕ работает:"
echo "   curl 'https://api.telegram.org/bot8508895640:AAHFMGty1dQRwZ03uU0zRiRnLKkQaOlrSI8/getMe'"
echo "   # Должно вернуть: {\"ok\":false,\"error_code\":401,\"description\":\"Unauthorized\"}"
echo ""
echo "5️⃣  Настройте credentials в n8n:"
echo "   https://n8n.alu.stella-spb.ru"
echo "   Settings → Credentials → Add Credential → Telegram"
echo "   Введите новый токен, сохраните как 'Telegram Bot'"
echo ""
echo "✅ После этого система будет полностью защищена!"
